name: CI

on:
  push:
  pull_request:
    types: [opened, edited]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: "yarn"
      - run: yarn
      - run: yarn format --validate
      - run: yarn build
